//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 11:49:24 PM ICT 
//


package model.entity.class_detail;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="ClassDetail">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ScheduleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Slot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="GroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Instructor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CourseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Campus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Present" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classDetail"
})
@XmlRootElement(name = "ClassDetails")
public class ClassDetails {

    @XmlElement(name = "ClassDetail")
    protected List<ClassDetails.ClassDetail> classDetail;

    /**
     * Gets the value of the classDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassDetails.ClassDetail }
     * 
     * 
     */
    public List<ClassDetails.ClassDetail> getClassDetail() {
        if (classDetail == null) {
            classDetail = new ArrayList<ClassDetails.ClassDetail>();
        }
        return this.classDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ScheduleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Slot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="GroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Instructor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CourseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Campus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Present" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scheduleId",
        "date",
        "slot",
        "groupName",
        "instructor",
        "courseName",
        "campus",
        "present"
    })
    public static class ClassDetail {

        @XmlElement(name = "ScheduleId")
        protected String scheduleId;
        @XmlElement(name = "Date")
        protected String date;
        @XmlElement(name = "Slot")
        protected String slot;
        @XmlElement(name = "GroupName")
        protected String groupName;
        @XmlElement(name = "Instructor")
        protected String instructor;
        @XmlElement(name = "CourseName")
        protected String courseName;
        @XmlElement(name = "Campus")
        protected String campus;
        @XmlElement(name = "Present")
        protected String present;

        /**
         * Gets the value of the scheduleId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduleId() {
            return scheduleId;
        }

        /**
         * Sets the value of the scheduleId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduleId(String value) {
            this.scheduleId = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the slot property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSlot() {
            return slot;
        }

        /**
         * Sets the value of the slot property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSlot(String value) {
            this.slot = value;
        }

        /**
         * Gets the value of the groupName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroupName() {
            return groupName;
        }

        /**
         * Sets the value of the groupName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroupName(String value) {
            this.groupName = value;
        }

        /**
         * Gets the value of the instructor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstructor() {
            return instructor;
        }

        /**
         * Sets the value of the instructor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstructor(String value) {
            this.instructor = value;
        }

        /**
         * Gets the value of the courseName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCourseName() {
            return courseName;
        }

        /**
         * Sets the value of the courseName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCourseName(String value) {
            this.courseName = value;
        }

        /**
         * Gets the value of the campus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCampus() {
            return campus;
        }

        /**
         * Sets the value of the campus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCampus(String value) {
            this.campus = value;
        }

        /**
         * Gets the value of the present property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPresent() {
            return present;
        }

        /**
         * Sets the value of the present property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPresent(String value) {
            this.present = value;
        }

    }

}
