//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.06 at 04:16:02 PM ICT 
//


package model.entity.schedule;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="Schedule"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ScheduleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="StudentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="StudentGroupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CourseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="RoomName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Slot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Instructor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Campus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schedule"
})
@XmlRootElement(name = "Schedules")
public class Schedules {

    @XmlElement(name = "Schedule")
    protected List<Schedules.Schedule> schedule;

    /**
     * Gets the value of the schedule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schedule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchedule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Schedules.Schedule }
     * 
     * 
     */
    public List<Schedules.Schedule> getSchedule() {
        if (schedule == null) {
            schedule = new ArrayList<Schedules.Schedule>();
        }
        return this.schedule;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ScheduleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="StudentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="StudentGroupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CourseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="RoomName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Slot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Instructor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Campus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scheduleId",
        "studentId",
        "studentGroupId",
        "courseName",
        "roomName",
        "date",
        "slot",
        "instructor",
        "campus"
    })
    public static class Schedule {

        @XmlElement(name = "ScheduleId")
        protected String scheduleId;
        @XmlElement(name = "StudentId")
        protected String studentId;
        @XmlElement(name = "StudentGroupId")
        protected String studentGroupId;
        @XmlElement(name = "CourseName")
        protected String courseName;
        @XmlElement(name = "RoomName")
        protected String roomName;
        @XmlElement(name = "Date")
        protected String date;
        @XmlElement(name = "Slot")
        protected String slot;
        @XmlElement(name = "Instructor")
        protected String instructor;
        @XmlElement(name = "Campus")
        protected String campus;

        /**
         * Gets the value of the scheduleId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduleId() {
            return scheduleId;
        }

        /**
         * Sets the value of the scheduleId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduleId(String value) {
            this.scheduleId = value;
        }

        /**
         * Gets the value of the studentId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStudentId() {
            return studentId;
        }

        /**
         * Sets the value of the studentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStudentId(String value) {
            this.studentId = value;
        }

        /**
         * Gets the value of the studentGroupId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStudentGroupId() {
            return studentGroupId;
        }

        /**
         * Sets the value of the studentGroupId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStudentGroupId(String value) {
            this.studentGroupId = value;
        }

        /**
         * Gets the value of the courseName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCourseName() {
            return courseName;
        }

        /**
         * Sets the value of the courseName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCourseName(String value) {
            this.courseName = value;
        }

        /**
         * Gets the value of the roomName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoomName() {
            return roomName;
        }

        /**
         * Sets the value of the roomName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoomName(String value) {
            this.roomName = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the slot property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSlot() {
            return slot;
        }

        /**
         * Sets the value of the slot property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSlot(String value) {
            this.slot = value;
        }

        /**
         * Gets the value of the instructor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstructor() {
            return instructor;
        }

        /**
         * Sets the value of the instructor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstructor(String value) {
            this.instructor = value;
        }

        /**
         * Gets the value of the campus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCampus() {
            return campus;
        }

        /**
         * Sets the value of the campus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCampus(String value) {
            this.campus = value;
        }

    }

}
