//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.05 at 03:49:52 PM ICT 
//


package model.entity.attendance;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="Attendance"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="StudentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ScheduleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="GroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CourseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Present" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attendance"
})
@XmlRootElement(name = "Attendances")
public class Attendances {

    @XmlElement(name = "Attendance")
    protected List<Attendances.Attendance> attendance;

    /**
     * Gets the value of the attendance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attendance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttendance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attendances.Attendance }
     * 
     * 
     */
    public List<Attendances.Attendance> getAttendance() {
        if (attendance == null) {
            attendance = new ArrayList<Attendances.Attendance>();
        }
        return this.attendance;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="StudentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ScheduleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="GroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CourseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Present" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "studentId",
        "scheduleId",
        "groupName",
        "courseName",
        "present"
    })
    public static class Attendance {

        @XmlElement(name = "StudentId")
        protected String studentId;
        @XmlElement(name = "ScheduleId")
        protected String scheduleId;
        @XmlElement(name = "GroupName")
        protected String groupName;
        @XmlElement(name = "CourseName")
        protected String courseName;
        @XmlElement(name = "Present")
        protected String present;

        /**
         * Gets the value of the studentId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStudentId() {
            return studentId;
        }

        /**
         * Sets the value of the studentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStudentId(String value) {
            this.studentId = value;
        }

        /**
         * Gets the value of the scheduleId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduleId() {
            return scheduleId;
        }

        /**
         * Sets the value of the scheduleId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduleId(String value) {
            this.scheduleId = value;
        }

        /**
         * Gets the value of the groupName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroupName() {
            return groupName;
        }

        /**
         * Sets the value of the groupName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroupName(String value) {
            this.groupName = value;
        }

        /**
         * Gets the value of the courseName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCourseName() {
            return courseName;
        }

        /**
         * Sets the value of the courseName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCourseName(String value) {
            this.courseName = value;
        }

        /**
         * Gets the value of the present property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPresent() {
            return present;
        }

        /**
         * Sets the value of the present property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPresent(String value) {
            this.present = value;
        }

    }

}
